name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -scheme PlaygroundTester -destination 'platform=iOS Simulator,OS=15.2,name=iPhone 13'
    - name: Run tests
      run: xcodebuild -scheme PlaygroundTester -destination 'platform=iOS Simulator,OS=15.2,name=iPhone 13' test
